const EXTREME_PROFANITY_FILTER_LIST = [
    "2 girls 1 cup",
    "2g1c",
    "4r5e",
    "5h1t",
    "5hit",
    "a_s_s",
    "a55",
    "a55hole",
    "acrotomophilia",
    "aeolus",
    "ahole",
    "alabama hot pocket",
    "alaskan pipeline",
    "anal",
    "analprobe",
    "anilingus",
    "anus",
    "apeshit",
    "ar5e",
    "areola",
    "areole",
    "arian",
    "arrse",
    "arse",
    "arsehole",
    "aryan",
    "ass",
    "ass hole",
    "assbag",
    "assbandit",
    "assbang",
    "assbanged",
    "assbanger",
    "assbangs",
    "assbite",
    "assclown",
    "asscock",
    "asscracker",
    "asses",
    "assface",
    "assfuck",
    "assfucker",
    "ass-fucker",
    "assfukka",
    "assgoblin",
    "assh0le",
    "asshat",
    "ass-hat",
    "asshead",
    "assho1e",
    "asshole",
    "assholes",
    "asshopper",
    "ass-jabber",
    "assjacker",
    "asslick",
    "asslicker",
    "assmaster",
    "assmonkey",
    "assmunch",
    "assmuncher",
    "assnigger",
    "asspirate",
    "ass-pirate",
    "assshit",
    "assshole",
    "asssucker",
    "asswad",
    "asswhole",
    "asswipe",
    "asswipes",
    "auto erotic",
    "autoerotic",
    "axwound",
    "azazel",
    "azz",
    "b!tch",
    "b00bs",
    "b17ch",
    "b1tch",
    "babe",
    "babeland",
    "babes",
    "baby batter",
    "baby juice",
    "balls",
    "ball gag",
    "ball gravy",
    "ball kicking",
    "ball licking",
    "ball sack",
    "ball sucking",
    "ballbag",
    "ballsack",
    "bampot",
    "bang",
    "bangbros",
    "banger",
    "bareback",
    "barely legal",
    "barenaked",
    "barf",
    "bastard",
    "bastardo",
    "bastards",
    "bastinado",
    "bawdy",
    "bbw",
    "bdsm",
    "beaner",
    "beaners",
    "beardedclam",
    "beastial",
    "beastiality",
    "beatch",
    "beater",
    "beaver cleaver",
    "beaver lips",
    "beeyotch",
    "bellend",
    "beotch",
    "bestial",
    "bestiality",
    "bi+ch",
    "biatch",
    "big black",
    "big breasts",
    "big knockers",
    "big tits",
    "bigtits",
    "bimbo",
    "bimbos",
    "birdlock",
    "bitch",
    "bitchass",
    "bitched",
    "bitcher",
    "bitchers",
    "bitches",
    "bitchin",
    "bitching",
    "bitchtits",
    "bitchy",
    "black cock",
    "blonde action",
    "blonde on blonde action",
    "blow job",
    "blow your load",
    "blowjob",
    "blowjobs",
    "blue waffle",
    "blumpkin",
    "bod",
    "bodily",
    "boink",
    "boiolas",
    "bollock",
    "bollocks",
    "bollok",
    "bollox",
    "bondage",
    "boned",
    "boner",
    "boners",
    "bong",
    "boob",
    "boobies",
    "boobs",
    "booby",
    "booger",
    "bookie",
    "booobs",
    "boooobs",
    "booooobs",
    "booooooobs",
    "bootee",
    "bootie",
    "booty",
    "booty call",
    "booze",
    "boozer",
    "boozy",
    "bosom",
    "bosomy",
    "bra",
    "brassiere",
    "breast",
    "breasts",
    "breeder",
    "brotherfucker",
    "brown showers",
    "brunette action",
    "buceta",
    "bugger",
    "bukkake",
    "bull shit",
    "bulldyke",
    "bullet vibe",
    "bullshit",
    "bullshits",
    "bullshitted",
    "bullturds",
    "bum",
    "bumblefuck",
    "bung",
    "bung hole",
    "bunghole",
    "bunny fucker",
    "busty",
    "butt",
    "butt fuck",
    "butt plug",
    "buttcheeks",
    "buttfuck",
    "buttfucka",
    "buttfucker",
    "butthole",
    "buttmuch",
    "butt-pirate",
    "buttplug",
    "c.0.c.k",
    "c.o.c.k.",
    "c.u.n.t",
    "c0ck",
    "c-0-c-k",
    "c0cksucker",
    "caca",
    "cahone",
    "camel toe",
    "cameltoe",
    "camgirl",
    "camslut",
    "camwhore",
    "carpet muncher",
    "carpetmuncher",
    "cawk",
    "cervix",
    "chesticle",
    "chinc",
    "chincs",
    "chink",
    "choad",
    "chocolate rosebuds",
    "chode",
    "chodes",
    "cipa",
    "circlejerk",
    "cl1t",
    "cleveland steamer",
    "climax",
    "clit",
    "clitface",
    "clitfuck",
    "clitoris",
    "clitorus",
    "clits",
    "clitty",
    "clover clamps",
    "clusterfuck",
    "cnut",
    "cocain",
    "cocaine",
    "cock",
    "c-o-c-k",
    "cock sucker",
    "cockass",
    "cockbite",
    "cockblock",
    "cockburger",
    "cockeye",
    "cockface",
    "cockfucker",
    "cockhead",
    "cockholster",
    "cockjockey",
    "cockknocker",
    "cockknoker",
    "cocklump",
    "cockmaster",
    "cockmongler",
    "cockmongruel",
    "cockmonkey",
    "cockmunch",
    "cockmuncher",
    "cocknose",
    "cocknugget",
    "cocks",
    "cockshit",
    "cocksmith",
    "cocksmoke",
    "cocksmoker",
    "cocksniffer",
    "cocksuck",
    "cocksucked",
    "cocksucker",
    "cock-sucker",
    "cocksucking",
    "cocksucks",
    "cocksuka",
    "cocksukka",
    "cockwaffle",
    "coital",
    "cok",
    "cokmuncher",
    "coksucka",
    "commie",
    "condom",
    "coochie",
    "coochy",
    "coon",
    "coons",
    "cooter",
    "coprolagnia",
    "coprophilia",
    "corksucker",
    "cornhole",
    "cox",
    "crabs",
    "crack",
    "crackwhore",
    "crap",
    "crappy",
    "creampie",
    "crotte",
    "cum",
    "cumbubble",
    "cumdumpster",
    "cumguzzler",
    "cumjockey",
    "cummer",
    "cummin",
    "cumming",
    "cums",
    "cumshot",
    "cumshots",
    "cumslut",
    "cumstain",
    "cumtart",
    "cunilingus",
    "cunillingus",
    "cunnie",
    "cunnilingus",
    "cunny",
    "cunt",
    "c-u-n-t",
    "cuntass",
    "cuntface",
    "cunthole",
    "cunthunter",
    "cuntlick",
    "cuntlicker",
    "cuntlicking",
    "cuntrag",
    "cunts",
    "cuntslut",
    "cyalis",
    "cyberfuc",
    "cyberfuck",
    "cyberfucked",
    "cyberfucker",
    "cyberfuckers",
    "cyberfucking",
    "d0ng",
    "d0uch3",
    "d0uche",
    "d1ck",
    "d1ld0",
    "d1ldo",
    "dago",
    "dagos",
    "darkie",
    "damn",
    "damned",
    "dammit",
    "date rape",
    "daterape",
    "dawgie-style",
    "deep throat",
    "deepthroat",
    "deggo",
    "dendrophilia",
    "dick",
    "dickbag",
    "dickbeaters",
    "dickdipper",
    "dickface",
    "dickflipper",
    "dickfuck",
    "dickfucker",
    "dickhead",
    "dickheads",
    "dickhole",
    "dickish",
    "dick-ish",
    "dickjuice",
    "dickmilk",
    "dickmonger",
    "dickripper",
    "dicks",
    "dicksipper",
    "dickslap",
    "dick-sneeze",
    "dicksuck",
    "dicksucker",
    "dicksucking",
    "dicktickler",
    "dickwad",
    "dickweasel",
    "dickweed",
    "dickwhipper",
    "dickwod",
    "dickzipper",
    "diddle",
    "dike",
    "dildo",
    "dildos",
    "diligaf",
    "dillweed",
    "dimwit",
    "dingle",
    "dingleberries",
    "dingleberry",
    "dink",
    "dinks",
    "dipship",
    "dipshit",
    "dirsa",
    "dirty pillows",
    "dirty sanchez",
    "dlck",
    "dog style",
    "dog-fucker",
    "doggie style",
    "doggiestyle",
    "doggie-style",
    "doggin",
    "dogging",
    "doggy style",
    "doggystyle",
    "doggy-style",
    "dolcett",
    "domination",
    "dominatrix",
    "dommes",
    "dong",
    "donkey punch",
    "donkeyribber",
    "doochbag",
    "doofus",
    "dookie",
    "doosh",
    "dopey",
    "double dong",
    "double penetration",
    "doublelift",
    "douch3",
    "douche",
    "douchebag",
    "douchebags",
    "douche-fag",
    "douchewaffle",
    "douchey",
    "dp action",
    "drunk",
    "dry hump",
    "duche",
    "dumass",
    "dumb ass",
    "dumbass",
    "dumbasses",
    "dumbcunt",
    "dumbfuck",
    "dumbshit",
    "dummy",
    "dumshit",
    "dvda",
    "dyke",
    "dykes",
    "eat my ass",
    "ecchi",
    "ejaculate",
    "ejaculated",
    "ejaculates",
    "ejaculating",
    "ejaculatings",
    "ejaculation",
    "ejakulate",
    "enlargement",
    "erect",
    "erection",
    "erotic",
    "erotism",
    "escort",
    "essohbee",
    "eunuch",
    "extacy",
    "extasy",
    "f u c k",
    "f u c k e r",
    "f.u.c.k",
    "f_u_c_k",
    "f4nny",
    "fack",
    "fag",
    "fagbag",
    "fagfucker",
    "fagg",
    "fagged",
    "fagging",
    "faggit",
    "faggitt",
    "faggot",
    "faggotcock",
    "faggs",
    "fagot",
    "fagots",
    "fags",
    "fagtard",
    "faig",
    "faigt",
    "fanny",
    "fannybandit",
    "fannyflaps",
    "fannyfucker",
    "fanyy",
    "fartknocker",
    "fatass",
    "fcuk",
    "fcuker",
    "fcuking",
    "fecal",
    "feck",
    "fecker",
    "felch",
    "felcher",
    "felching",
    "fellate",
    "fellatio",
    "feltch",
    "feltcher",
    "female squirting",
    "femdom",
    "figging",
    "fingerbang",
    "fingerfuck",
    "fingerfucked",
    "fingerfucker",
    "fingerfuckers",
    "fingerfucking",
    "fingerfucks",
    "fingering",
    "fisted",
    "fistfuck",
    "fistfucked",
    "fistfucker",
    "fistfuckers",
    "fistfucking",
    "fistfuckings",
    "fistfucks",
    "fisting",
    "fisty",
    "flamer",
    "flange",
    "floozy",
    "foad",
    "foah",
    "fondle",
    "foobar",
    "fook",
    "fooker",
    "foot fetish",
    "footjob",
    "foreskin",
    "freex",
    "frigg",
    "frigga",
    "frotting",
    "fubar",
    "fuck",
    "f-u-c-k",
    "fuck buttons",
    "fuck off",
    "fucka",
    "fuckass",
    "fuckbag",
    "fuckboy",
    "fuckbrain",
    "fuckbutt",
    "fuckbutter",
    "fucked",
    "fucker",
    "fuckers",
    "fuckersucker",
    "fuckface",
    "fuckhead",
    "fuckheads",
    "fuckhole",
    "fuckin",
    "fucking",
    "fuckings",
    "fuckingshitmotherfucker",
    "fuckme",
    "fucknugget",
    "fucknut",
    "fucknutt",
    "fuckoff",
    "fucks",
    "fuckstick",
    "fucktard",
    "fuck-tard",
    "fucktards",
    "fucktart",
    "fucktwat",
    "fuckup",
    "fuckwad",
    "fuckwhit",
    "fuckwit",
    "fuckwitt",
    "fudge packer",
    "fudgepacker",
    "fuk",
    "fuker",
    "fukker",
    "fukkin",
    "fuks",
    "fukwhit",
    "fukwit",
    "futanari",
    "fux",
    "fux0r",
    "fvck",
    "fxck",
    "gae",
    "gai",
    "gang bang",
    "gangbang",
    "gangbanged",
    "gangbangs",
    "ganja",
    "gay",
    "gay sex",
    "gayass",
    "gaybob",
    "gaydo",
    "gayfuck",
    "gayfuckist",
    "gaylord",
    "gays",
    "gaysex",
    "gaytard",
    "gaywad",
    "genitals",
    "gey",
    "gfy",
    "ghay",
    "ghey",
    "giant cock",
    "gigolo",
    "girl on",
    "girl on top",
    "girls gone wild",
    "glans",
    "goatcx",
    "goatse",
    "god damn",
    "godamn",
    "godamnit",
    "goddam",
    "god-dam",
    "goddammit",
    "goddamn",
    "goddamned",
    "god-damned",
    "goddamnit",
    "gokkun",
    "golden shower",
    "goldenshower",
    "gonad",
    "gonads",
    "goo girl",
    "gooch",
    "goodpoop",
    "gook",
    "gooks",
    "goregasm",
    "gringo",
    "grope",
    "group sex",
    "gspot",
    "g-spot",
    "gtfo",
    "guido",
    "guro",
    "h0m0",
    "h0mo",
    "hand job",
    "handjob",
    "hard core",
    "hard on",
    "hardcore",
    "hardcoresex",
    "he11",
    "heeb",
    "hemp",
    "hentai",
    "heroin",
    "herp",
    "herpes",
    "herpy",
    "heshe",
    "hitler",
    "hiv",
    "ho",
    "hoar",
    "hoare",
    "hobag",
    "hoe",
    "hoer",
    "hom0",
    "homey",
    "homo",
    "homodumbshit",
    "homoerotic",
    "homoey",
    "honkey",
    "honky",
    "hooch",
    "hookah",
    "hooker",
    "hoor",
    "hootch",
    "hooter",
    "hooters",
    "hore",
    "horniest",
    "horny",
    "hot carl",
    "hot chick",
    "hotsex",
    "how to kill",
    "how to murder",
    "huge fat",
    "hump",
    "humped",
    "humping",
    "hussy",
    "hymen",
    "inbred",
    "incest",
    "injun",
    "intercourse",
    "j3rk0ff",
    "jack Off",
    "jackass",
    "jackhole",
    "jackoff",
    "jack-off",
    "jaggi",
    "jagoff",
    "jail bait",
    "jailbait",
    "jap",
    "japs",
    "jelly donut",
    "jerk",
    "jerk off",
    "jerk0ff",
    "jerkass",
    "jerked",
    "jerkoff",
    "jerk-off",
    "jigaboo",
    "jiggaboo",
    "jiggerboo",
    "jism",
    "jiz",
    "jizm",
    "jizz",
    "jizzed",
    "juggs",
    "jungle bunny",
    "junglebunny",
    "junkie",
    "junky",
    "kawk",
    "kike",
    "kikes",
    "kinbaku",
    "kinkster",
    "kinky",
    "kkk",
    "knob",
    "knobbing",
    "knobead",
    "knobed",
    "knobend",
    "knobhead",
    "knobjocky",
    "knobjokey",
    "kock",
    "kondum",
    "kondums",
    "kooch",
    "kooches",
    "kootch",
    "kraut",
    "kum",
    "kummer",
    "kumming",
    "kums",
    "kunilingus",
    "kunja",
    "kunt",
    "kyke",
    "l3i+ch",
    "l3itch",
    "labia",
    "lameass",
    "lardass",
    "leather restraint",
    "leather straight jacket",
    "lech",
    "lemon party",
    "leper",
    "lesbian",
    "lesbians",
    "lesbo",
    "lesbos",
    "lez",
    "lezbian",
    "lezbians",
    "lezbo",
    "lezbos",
    "lezzie",
    "lezzies",
    "lezzy",
    "lmao",
    "lmfao",
    "loin",
    "loins",
    "lolita",
    "lovemaking",
    "lube",
    "lust",
    "lusting",
    "lusty",
    "m0f0",
    "m0fo",
    "m45terbate",
    "ma5terb8",
    "ma5terbate",
    "make me come",
    "male squirting",
    "mams",
    "masochist",
    "massa",
    "masterb8",
    "masterbat",
    "masterbat3",
    "masterbate",
    "master-bate",
    "masterbating",
    "masterbation",
    "masterbations",
    "masturbate",
    "masturbating",
    "masturbation",
    "maxi",
    "mcfagget",
    "menage a trois",
    "menses",
    "menstruate",
    "menstruation",
    "meth",
    "m-fucking",
    "mick",
    "milf",
    "minge",
    "missionary position",
    "mof0",
    "mofo",
    "mo-fo",
    "molest",
    "moolie",
    "moron",
    "mothafuck",
    "mothafucka",
    "mothafuckas",
    "mothafuckaz",
    "mothafucked",
    "mothafucker",
    "mothafuckers",
    "mothafuckin",
    "mothafucking",
    "mothafuckings",
    "mothafucks",
    "mother fucker",
    "motherfuck",
    "motherfucka",
    "motherfucked",
    "motherfucker",
    "motherfuckers",
    "motherfuckin",
    "motherfucking",
    "motherfuckings",
    "motherfuckka",
    "motherfucks",
    "mound of venus",
    "mr hands",
    "mtherfucker",
    "mthrfucker",
    "mthrfucking",
    "muff",
    "muff diver",
    "muffdiver",
    "muffdiving",
    "munging",
    "murder",
    "mutha",
    "muthafecker",
    "muthafuckaz",
    "muthafucker",
    "muthafuckker",
    "muther",
    "mutherfucker",
    "mutherfucking",
    "muthrfucking",
    "n1gga",
    "n1gger",
    "nad",
    "nads",
    "naked",
    "nambla",
    "napalm",
    "nappy",
    "nawashi",
    "nazi",
    "nazism",
    "negro",
    "neonazi",
    "nig nog",
    "nigaboo",
    "nigg3r",
    "nigg4h",
    "nigga",
    "niggah",
    "niggas",
    "niggaz",
    "nigger",
    "niggers",
    "niggle",
    "niglet",
    "nimphomania",
    "nimrod",
    "ninny",
    "nipple",
    "nipples",
    "nob",
    "nob jokey",
    "nobhead",
    "nobjocky",
    "nobjokey",
    "nooky",
    "nsfw images",
    "nude",
    "nudity",
    "numbnuts",
    "nut sack",
    "nutsack",
    "nympho",
    "nymphomania",
    "octopussy",
    "omorashi",
    "one cup two girls",
    "one guy one jar",
    "opiate",
    "opium",
    "oral",
    "orally",
    "organ",
    "orgasim",
    "orgasims",
    "orgasm",
    "orgasmic",
    "orgasms",
    "orgies",
    "orgy",
    "ovary",
    "ovum",
    "ovums",
    "p.u.s.s.y.",
    "p0rn",
    "paddy",
    "paedophile",
    "paki",
    "panooch",
    "pantie",
    "panties",
    "panty",
    "pastie",
    "pasty",
    "pawn",
    "pcp",
    "pecker",
    "peckerhead",
    "pedo",
    "pedobear",
    "pedophile",
    "pedophilia",
    "pedophiliac",
    "peepee",
    "pegging",
    "penetrate",
    "penetration",
    "penial",
    "penile",
    "penis",
    "penisbanger",
    "penisfucker",
    "penispuffer",
    "perversion",
    "peyote",
    "phalli",
    "phallic",
    "phone sex",
    "phonesex",
    "phuck",
    "phuk",
    "phuked",
    "phuking",
    "phukked",
    "phukking",
    "phuks",
    "phuq",
    "piece of shit",
    "pigfucker",
    "pillowbiter",
    "pimp",
    "pimpis",
    "pinko",
    "piss pig",
    "pissed",
    "pissed off",
    "pisser",
    "pissers",
    "pisses",
    "pissflaps",
    "pissin",
    "pissing",
    "pissoff",
    "piss-off",
    "pisspig",
    "playboy",
    "pleasure chest",
    "pms",
    "polack",
    "pole smoker",
    "polesmoker",
    "pollock",
    "ponyplay",
    "poof",
    "poon",
    "poonani",
    "poonany",
    "poontang",
    "poop",
    "poop chute",
    "poopchute",
    "poopuncher",
    "porch monkey",
    "porchmonkey",
    "porn",
    "porno",
    "pornography",
    "pornos",
    "potty",
    "prick",
    "pricks",
    "prig",
    "prince albert piercing",
    "pron",
    "prostitute",
    "prude",
    "pthc",
    "pube",
    "pubes",
    "pubic",
    "pubis",
    "punanny",
    "punany",
    "punkass",
    "punky",
    "punta",
    "puss",
    "pusse",
    "pussi",
    "pussies",
    "pussy",
    "pussylicking",
    "pussypounder",
    "pussys",
    "pust",
    "puto",
    "queaf",
    "queef",
    "queer",
    "queerbait",
    "queerhole",
    "queero",
    "queers",
    "quicky",
    "quim",
    "racy",
    "raghead",
    "raging boner",
    "rape",
    "raped",
    "raper",
    "raping",
    "rapist",
    "raunch",
    "rectal",
    "rectum",
    "rectus",
    "reefer",
    "reetard",
    "reich",
    "renob",
    "retard",
    "retarded",
    "reverse cowgirl",
    "revue",
    "rimjaw",
    "rimjob",
    "rimming",
    "ritard",
    "rosy palm",
    "rosy palm and her 5 sisters",
    "rtard",
    "r-tard",
    "rump",
    "rumprammer",
    "ruski",
    "rusty trombone",
    "s hit",
    "s&m",
    "s.h.i.t.",
    "s.o.b.",
    "s_h_i_t",
    "s0b",
    "sadism",
    "sadist",
    "sand nigger",
    "sandler",
    "sandnigger",
    "sanger",
    "santorum",
    "scag",
    "scantily",
    "scat",
    "schizo",
    "schlong",
    "scissoring",
    "screw",
    "screwed",
    "screwing",
    "scroat",
    "scrog",
    "scrot",
    "scrote",
    "scrotum",
    "scrud",
    "scum",
    "seaman",
    "seamen",
    "seduce",
    "seks",
    "semen",
    "sex",
    "sexo",
    "sexual",
    "sexy",
    "sh!+",
    "sh!t",
    "sh1t",
    "s-h-1-t",
    "shag",
    "shagger",
    "shaggin",
    "shagging",
    "shamedame",
    "shaved beaver",
    "shaved pussy",
    "shemale",
    "shi+",
    "shibari",
    "shit",
    "s-h-i-t",
    "shitass",
    "shitbag",
    "shitbagger",
    "shitblimp",
    "shitbrains",
    "shitbreath",
    "shitcanned",
    "shitcunt",
    "shitdick",
    "shite",
    "shiteater",
    "shited",
    "shitey",
    "shitface",
    "shitfaced",
    "shitfuck",
    "shitfull",
    "shithead",
    "shithole",
    "shithouse",
    "shiting",
    "shitings",
    "shits",
    "shitspitter",
    "shitstain",
    "shitt",
    "shitted",
    "shitter",
    "shitters",
    "shittiest",
    "shitting",
    "shittings",
    "shitty",
    "shiz",
    "shiznit",
    "shota",
    "shrimping",
    "sissy",
    "skag",
    "skank",
    "skeet",
    "skullfuck",
    "slag",
    "slanteye",
    "slave",
    "sleaze",
    "sleazy",
    "slut",
    "slutbag",
    "slutdumper",
    "slutkiss",
    "sluts",
    "smeg",
    "smegma",
    "smut",
    "smutty",
    "snatch",
    "snowballing",
    "snuff",
    "s-o-b",
    "sodom",
    "sodomize",
    "sodomy",
    "son-of-a-bitch",
    "souse",
    "soused",
    "spac",
    "sperm",
    "spic",
    "spick",
    "spik",
    "spiks",
    "splooge",
    "splooge moose",
    "spooge",
    "spook",
    "spread legs",
    "spunk",
    "steamy",
    "stfu",
    "stiffy",
    "stoned",
    "strap on",
    "strapon",
    "strappado",
    "strip",
    "strip club",
    "stroke",
    "stupid",
    "style doggy",
    "suck",
    "suckass",
    "sucked",
    "sucking",
    "suckmydick",
    "sucks",
    "suicide girls",
    "sultry women",
    "sumofabiatch",
    "swastika",
    "swinger",
    "t1t",
    "t1tt1e5",
    "t1tties",
    "tainted love",
    "tampon",
    "tard",
    "taste my",
    "tawdry",
    "tea bagging",
    "teabagging",
    "teat",
    "teets",
    "teez",
    "terd",
    "teste",
    "testee",
    "testes",
    "testical",
    "testicle",
    "testis",
    "threesome",
    "throating",
    "thrust",
    "thug",
    "thundercunt",
    "tied up",
    "tight white",
    "tinkle",
    "tit",
    "titfuck",
    "titi",
    "tits",
    "titt",
    "tittie5",
    "tittiefucker",
    "titties",
    "titty",
    "tittyfuck",
    "tittyfucker",
    "tittywank",
    "titwank",
    "toke",
    "tongue in a",
    "toots",
    "topless",
    "tosser",
    "towelhead",
    "tramp",
    "tranny",
    "transsexual",
    "trashy",
    "tribadism",
    "tub girl",
    "tubgirl",
    "turd",
    "tush",
    "tushy",
    "tw4t",
    "twat",
    "twathead",
    "twatlips",
    "twats",
    "twatty",
    "twatwaffle",
    "twink",
    "twinkie",
    "two girls one cup",
    "twunt",
    "twunter",
    "ugly",
    "unclefucker",
    "undies",
    "undressing",
    "unwed",
    "upskirt",
    "urethra play",
    "urinal",
    "urine",
    "urophilia",
    "uterus",
    "uzi",
    "v14gra",
    "v1gra",
    "vag",
    "vagina",
    "vajayjay",
    "va-j-j",
    "valium",
    "venus mound",
    "viagra",
    "vibrator",
    "violet wand",
    "virgin",
    "vixen",
    "vjayjay",
    "vodka",
    "vomit",
    "vorarephilia",
    "voyeur",
    "vulgar",
    "vulva",
    "w00se",
    "wad",
    "wang",
    "wank",
    "wanker",
    "wankjob",
    "wanky",
    "wazoo",
    "wedgie",
    "weed",
    "weenie",
    "weewee",
    "weiner",
    "weirdo",
    "wench",
    "wet dream",
    "wetback",
    "wh0re",
    "wh0reface",
    "white power",
    "whitey",
    "whiz",
    "whoar",
    "whoralicious",
    "whore",
    "whorealicious",
    "whorebag",
    "whored",
    "whoreface",
    "whorehopper",
    "whorehouse",
    "whores",
    "whoring",
    "wigger",
    "willies",
    "willy",
    "womb",
    "woody",
    "wop",
    "wrapping men",
    "wrinkled starfish",
    "wtf",
    "xrated",
    "x-rated",
    "xxx",
    "yaoi",
    "yeasty",
    "yellow showers",
    "yiffy",
    "yobbo",
    "zoophile",
    "zoophilia",
    "zubb",
    "(ock",
    "[ock",
    ".f uc k",
    "@rse",
    "@rsehol",
    "@unt",
    "[unt",
    "< unt",
    "<.unt",
    "<loth head",
    "<lothhead",
    "<nuts",
    "<o(k",
    "<o<&nbsp;k",
    "<o<ksu<ka",
    "<o<ksu<ker",
    "<oon",
    "<u&nbsp;nt",
    "<u&nbsp;nts",
    "<u*t",
    "<unt",
    "<unt's",
    "<vnt",
    "<vnts",
    "a$$hole",
    "a$$hole$",
    "a$$holes",
    "a.rse",
    "a+*hole",
    "ar$ehole",
    "ar$hole",
    "ar$holes",
    "ar5h0le",
    "ar5h0les",
    "ars3",
    "arse hole",
    "arseh0le",
    "arseh0les",
    "arseho",
    "arsehol",
    "arseholes",
    "arsewipe",
    "arsh0le",
    "arshole",
    "arsholes",
    "ashole",
    "ass h0le",
    "assh0les",
    "b.astard",
    "b.ollocks",
    "b.ugger",
    "b@st@rd",
    "b@st@rds",
    "b00tha",
    "b00thas",
    "b0ll0cks",
    "b0llocks",
    "b3llend",
    "basterd",
    "basyard",
    "basyards",
    "batty boy",
    "batty&nbsp;boi",
    "batty&nbsp;boy",
    "beef curtains",
    "belend",
    "bell end",
    "bell.end",
    "bell-end",
    "bin dippers",
    "bin-dippers",
    "bo11ocks",
    "boabie sooking",
    "boaby sooking",
    "boll0cks",
    "bolocks",
    "bolox",
    "bootha",
    "boothas",
    "bum bandit",
    "bum hole",
    "bumbandit",
    "bum-bandit",
    "bumh0l3",
    "bumh0le",
    "bumhol3",
    "bumhole",
    "c *nt!",
    "c *nts!",
    "c u n t",
    "c u n t.",
    "c#nt",
    "c&nbsp;u&nbsp;n&nbsp;t",
    "c* nt",
    "c.unt",
    "c.untyb.ollocks",
    "c_u_n_t",
    "c00n",
    "c0cksucka",
    "cahnt",
    "cahnts",
    "clunge",
    "cnuts",
    "co(k",
    "coc&nbsp;k",
    "cocksucka",
    "cocksuckers",
    "cocksuckers.",
    "cossor ali",
    "cretin",
    "cripple",
    "critest",
    "cu&nbsp;nt",
    "cu&nbsp;nts",
    "cunting",
    "cunt's",
    "cvnt",
    "cvnts",
    "d1ck!",
    "d1ckh@ed",
    "darky",
    "dick&nbsp;head",
    "dumbfucker",
    "dxxkhead",
    "ethnics",
    "f ck",
    "f o a d",
    "f off",
    "f u c ked",
    "f uc k",
    "f uc king",
    "f uck",
    "f###",
    "f##k",
    "f##king",
    "f#cked",
    "f$cks",
    "f&nbsp;cked",
    "f&nbsp;u&nbsp;c&nbsp;k",
    "f&nbsp;uck",
    "f&nbsp;ucker",
    "f&nbsp;ucking",
    "f()()k",
    "f()()ker",
    "f()()king",
    "f*#kin'",
    "f*&k",
    "f*&k!ng",
    "f.o.a.d",
    "f.o.a.d.",
    "f.u.c.k.",
    "f.uck",
    "f@@@in",
    "f@@@ing",
    "f@ck",
    "f@g",
    "f@gs",
    "f[_]cker",
    "f[_]cking",
    "f^^k",
    "f^^ked",
    "f^^ker",
    "f^^king",
    "f^ck",
    "f^cker",
    "f^cking",
    "f__kin",
    "f__king",
    "f<uk",
    "f>>k",
    "f00k",
    "f00ked",
    "f0oked",
    "fackin",
    "facking",
    "f4ggot",
    "f4gg0t",
    "fagg0t",
    "faggits",
    "fagits",
    "fck",
    "f'ck",
    "fck&nbsp;ing",
    "fck1ng",
    "fckeud",
    "fckin",
    "fcking",
    "fcks",
    "fckw1t",
    "fckwit",
    "fcuked",
    "fcukin",
    "fcuks",
    "feckin",
    "fecking",
    "f---ed",
    "fekking",
    "felched",
    "feltching",
    "f-----g",
    "f---ing",
    "f--k",
    "fkin",
    "fking",
    "flucknuts",
    "fo0ked",
    "f-o-a-d",
    "fookd",
    "fooked",
    "fookin",
    "fookin'",
    "fooking",
    "frig",
    "frigging",
    "frigin",
    "friging",
    "fu <k",
    "fu&kin",
    "fu&king",
    "fu&nbsp;ck",
    "fu&nbsp;cked",
    "fu&nbsp;cker",
    "fu&nbsp;cking",
    "fu(k",
    "fu(ker",
    "fu(kers",
    "fu.ck",
    "fu@k",
    "fu@ker",
    "fu^k",
    "fu^ker",
    "fu^king",
    "fu< kin",
    "fu<k",
    "f-u-<-k",
    "fu<ked",
    "fu<ker",
    "fu<kin",
    "fu<king",
    "fu<kker",
    "fu<kr",
    "fu<ks",
    "fuc&nbsp;ked",
    "fuc&nbsp;ker",
    "fuc&nbsp;king",
    "f-uck",
    "fúck",
    "fúçk",
    "fùck",
    "fûck",
    "fück",
    "fuck&nbsp;ed",
    "fuck&nbsp;ing",
    "fucke&nbsp;d",
    "fucki&nbsp;ng",
    "fúcking",
    "fuckinghell",
    "fuckk",
    "fuckw1t",
    "fuck-wit",
    "fuckwits",
    "fucw1t",
    "fucwit",
    "fudge p@cker",
    "fudgep@cker",
    "fudge-p@cker",
    "fudge-packer",
    "fudgpacker",
    "fukced",
    "fuked",
    "fukin",
    "fuking",
    "fukk",
    "fukked",
    "fukking",
    "fuukn",
    "fvckup",
    "fvck-up",
    "fvckw1t",
    "fvckwit",
    "gang-bang",
    "gash",
    "gayhole",
    "gimp",
    "girlie-gardening",
    "goris",
    "gypo",
    "gypos",
    "gyppo",
    "gyppos",
    "hvns",
    "israelians",
    "ities",
    "k@ffir",
    "k@ffirs",
    "k@fir",
    "k@firs",
    "kaf1r",
    "kaff1r",
    "kaffir",
    "kaffirs",
    "kafir",
    "kafirs",
    "kafr",
    "kants",
    "khunt",
    "kiddie fiddler",
    "kiddie fiddling",
    "kiddie-fiddler",
    "kiddie-fiddling",
    "kiddy fiddler",
    "kiddyfiddler",
    "kiddy-fiddler",
    "kn0b",
    "knob&nbsp;head",
    "knobber",
    "kuffar",
    "m.inge",
    "m.otherf.ucker",
    "m1nge",
    "mofuccer",
    "mofucker",
    "mofuckers",
    "mofucking",
    "mofukcer",
    "mohterfuccer",
    "mohterfuccers",
    "mohterfuck",
    "mohterfucker",
    "mohterfuckers",
    "mohterfucking",
    "mohterfucks",
    "mohterfuk",
    "mohterfukcer",
    "mohterfukcers",
    "mohterfuking",
    "mohterfuks",
    "moterfuccer",
    "moterfuck",
    "moterfucker",
    "moterfuckers",
    "moterfucking",
    "moterfucks",
    "mothafuccer",
    "motha-fucka",
    "mother f---ers",
    "motherfuccer",
    "motherfuccers",
    "motherfukkker",
    "mthafucca",
    "mthafuccas",
    "mthafucka",
    "mthafuckas",
    "mthafukca",
    "mthafukcas",
    "muff-diver",
    "muff-diving",
    "muffs",
    "muth@fucker",
    "muthafuccer",
    "muthafuck",
    "muthafuck@",
    "muthafucka",
    "muthafuckers",
    "muthafucking",
    "muthafucks",
    "muthafukas",
    "niga",
    "nignog",
    "nig-nog",
    "nob&nbsp;head",
    "nonce",
    "p.iss-flaps",
    "p@ki",
    "p@kis",
    "p00f",
    "p00fs",
    "p00fter",
    "p00fters",
    "p0of",
    "paedo",
    "paedophiles",
    "pak1",
    "pakis",
    "peado",
    "peadofile",
    "peadofiles",
    "peedo",
    "peedofile",
    "peedofiles",
    "peedophile",
    "peedophiles",
    "peedos",
    "pench0d",
    "pench0ds",
    "penchod",
    "penchods",
    "phanny",
    "phanny.",
    "pheck",
    "phecking",
    "phelching",
    "pheque",
    "phequing",
    "phucker",
    "phuckin",
    "phucking",
    "phucks",
    "pikey",
    "pillow biter",
    "pillow-biter",
    "piss off",
    "po0f",
    "poff",
    "ponce",
    "poo stabber",
    "poo stabbers",
    "poofs",
    "poofter",
    "pr!ck",
    "pr!ck.",
    "pr1ck",
    "pr1ck!",
    "pr1cks",
    "pr1cks!",
    "prik",
    "pu$$y",
    "ragheads",
    "ret@rd",
    "rim job",
    "s.hit",
    "s1ut",
    "sc u m!",
    "sc um",
    "sh hit",
    "sh!te",
    "sh!tes",
    "sh1te",
    "shirtlifter",
    "shirtlifters",
    "shit stabber",
    "shit stabbers",
    "shitstabber",
    "shitstabbers",
    "spastic",
    "spaz",
    "spaz.",
    "spit roasting",
    "spitroast",
    "spit-roast",
    "spit-roasting",
    "spunking",
    "ß0ll0çk5",
    "t w a t",
    "t wat",
    "t&nbsp;w&nbsp;a&nbsp;t",
    "t&nbsp;w&nbsp;a&nbsp;t&nbsp;s",
    "t.wat",
    "t0$$er",
    "t0sser",
    "t0ssers",
    "tea-bagging",
    "to55er",
    "to55ers",
    "tosser,",
    "tossers",
    "tossurs",
    "towel head",
    "tvvat",
    "tvvats",
    "tw at",
    "tw&nbsp;at",
    "tw@",
    "tw@t",
    "tw@ts",
    "tw_t",
    "twa t",
    "twatt",
    "twattish",
    "twunts",
    "up the gary",
    "w anker",
    "w ankers",
    "w#nker",
    "w#nkers",
    "w*nkers, 0",
    "w.ank",
    "w@nk",
    "w@nker",
    "w@nkers",
    "w@nks",
    "w0g",
    "w0gs",
    "w4nker!",
    "w4nkers!",
    "wa nker",
    "wan k er",
    "wan k ers",
    "wan ker",
    "wanka",
    "wanke r",
    "wanked",
    "wankers",
    "wanking",
    "wanks",
    "wank's",
    "wet spam",
    "whanker",
    "whankers",
    "wog",
    "xrse",
    "xrseh",
    "xrsehol",
    "xrsehole",
    "xxxhole",
    "y!ddo!",
    "y!ddo!!",
    "yid",
    "yido",
    "zachariah bishop",
    "blow-job",
    "boner:deboner",
    "bonk:bonkers",
    "candy-ass",
    "chuffnuts",
    "cojones",
    "dipstick",
    "feak",
    "furbox",
    "furburger",
    "gayboy",
    "ginch",
    "gnikcuf",
    "hardon",
    "honkers",
    "kcid",
    "kcuf",
    "lactoids",
    "lesbyterian",
    "lezzo",
    "man-root",
    "nestlecock",
    "onanism",
    "pusy",
    "queve",
    "quimsteak",
    "qveer",
    "sappho",
    "scumbag",
    "scumber",
    "sexpot",
    "shagbucket",
    "shagstress",
    "snarf",
    "sodomite",
    "strollop",
    "suckster",
    "tnuc",
    "toggaf",
    "tribadist",
    "twank",
    "wiseass",
    "wizzer",
];

let extremeLongestProfanity = 0;
const extremeProfanityFilterSet = {};
for (let i = 0; i < EXTREME_PROFANITY_FILTER_LIST.length; i++) {
    extremeLongestProfanity = Math.max(extremeLongestProfanity, EXTREME_PROFANITY_FILTER_LIST[i].length);
    extremeProfanityFilterSet[EXTREME_PROFANITY_FILTER_LIST[i]] = true;
}
